spring:
  application:
    name: modweave
  jpa:
    hibernate:
      ddl-auto: validate

minio:
  endpoint: http://localhost:9000
  credentials:
    username: miniosecretuser123
    password: miniosecretpass123
  buckets:
    mods: mods
    images: images

server:
  port: 8080