@host=http://localhost:8080
@accessToken=replace-with-access-token
@commentId=00000000-0000-0000-0000-000000000000

### Create comment
POST {{host}}/api/v1/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/x-www-form-urlencoded

content=This+mod+is+great&modId=example-mod

### Delete own comment (or any comment as an admin)
DELETE {{host}}/api/v1/comments/{{commentId}}
Authorization: Bearer {{accessToken}}
