@host=http://localhost:8080
@accessToken=replace-with-admin-access-token

### List games
GET {{host}}/api/v1/games?page=0&size=5

### Create game
POST {{host}}/api/v1/games
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=ModweaveBoundary

--ModweaveBoundary
Content-Disposition: form-data; name="name"

Example Game
--ModweaveBoundary
Content-Disposition: form-data; name="description"

Example game description
--ModweaveBoundary
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./image.png
--ModweaveBoundary--

### Delete game
DELETE {{host}}/api/v1/games/example-game
Authorization: Bearer {{accessToken}}
