@host=http://localhost:8080
@accessToken=replace-with-access-token

### List mods
GET {{host}}/api/v1/mods?page=0&size=5

### Get a mod
GET {{host}}/api/v1/mods/example-mod

### Upload mod with its first version
POST {{host}}/api/v1/mods
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=ModweaveBoundary

--ModweaveBoundary
Content-Disposition: form-data; name="name"

Example Mod
--ModweaveBoundary
Content-Disposition: form-data; name="description"

Example mod description
--ModweaveBoundary
Content-Disposition: form-data; name="gameId"

example-game
--ModweaveBoundary
Content-Disposition: form-data; name="versionName"

1.0.0
--ModweaveBoundary
Content-Disposition: form-data; name="categories"

Gameplay
--ModweaveBoundary
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./image.png
--ModweaveBoundary
Content-Disposition: form-data; name="files"; filename="example.txt"
Content-Type: text/plain

Example mod file
--ModweaveBoundary--

### Delete a mod
DELETE {{host}}/api/v1/mods/example-mod
Authorization: Bearer {{accessToken}}
