@host=localhost:8080

# Tokens
@accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YWxoYXkiLCJpc3MiOiJtb2R3ZWF2ZSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc4MTAyMDgyMSwiZXhwIjoxNzgxMDIxNzIxfQ.P807uzMkkUjTIi7XxvGCWM91FhuZoLNQd8x_zTgA3KE

### Get games

GET {{host}}/api/v1/mods?page=0&size=5

### Upload new game

POST {{host}}/api/v1/mods
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data

name=Game
description=My game desc
image=@./image.png
