@host=http://localhost:8080
@accessToken=replace-with-access-token

### Get user
GET {{host}}/api/v1/users/example

### List users
GET {{host}}/api/v1/users?page=0&size=5

### Register
POST {{host}}/api/v1/users
Content-Type: application/x-www-form-urlencoded

username=example&name=Example&email=example@example.com&password=example-password

### Update display name
PATCH {{host}}/api/v1/users
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{accessToken}}

name=New+name&email=new@example.com
