plugins {
  id 'org.springframework.boot'
}

dependencies {
  implementation project(':data-access')
  implementation project(':business-logic')
  implementation project(':ui')

  implementation 'org.springframework.boot:spring-boot-starter'
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  implementation 'org.springframework.boot:spring-boot-starter-data-redis'
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-cache'

  runtimeOnly 'org.postgresql:postgresql:42.7.3'

  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'org.springframework.boot:spring-boot-testcontainers'
  testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
  testImplementation platform('org.testcontainers:testcontainers-bom:2.0.4')
  testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
  testImplementation 'org.testcontainers:testcontainers-postgresql'
  testImplementation 'org.testcontainers:testcontainers-jdbc'
}
